[package]
name = "jira-tui"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
itertools = "0.14.0"
jira_v3_openapi = { version = "1.3.5", features = [
    "issues_api",
    "projects_api",
    "version_api"
] }
ratatui = "0.29.0"
tokio = { version = "1", features = ["full"] }
